title: Guillaume Delré
description: Tech articles about PHP, Symfony, API Platform and more.
url: "https://guillaumedelre.github.io"
author:
  name: Guillaume Delré
  email: delre.guillaume@gmail.com

theme: minima

image: /assets/images/og-default.jpg

header_pages:
  - categories.md
  - about.md

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-mentions

jekyll-mentions:
  base_url: https://github.com

permalink: /:year/:month/:day/:title/
